/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Moch Billy Refanto
 */
public class CRUD_Pengurus extends javax.swing.JFrame {

   
    public CRUD_Pengurus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tfJabatan = new javax.swing.JPanel();
        jlNamaLengkapPengurus = new javax.swing.JLabel();
        tfJabatanPengurus = new javax.swing.JTextField();
        tfAlamatLengkap = new javax.swing.JTextField();
        tfNamaPengurus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jlJabatan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfTanggalLahir = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnReset = new java.awt.Button();
        btnSimpan = new java.awt.Button();
        cbJenisKelamin = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JComboBox<>();
        tfKontakPengurus = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfKontakPengurus1 = new javax.swing.JTextField();
        btnReset1 = new java.awt.Button();
        btnSimpan1 = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(78, 115, 223));
        jPanel3.setToolTipText("");

        tfJabatan.setBackground(new java.awt.Color(255, 255, 255));
        tfJabatan.setToolTipText("");

        jlNamaLengkapPengurus.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jlNamaLengkapPengurus.setText("Nama Lengkap");

        tfJabatanPengurus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfJabatanPengurus.setMargin(new java.awt.Insets(3, 3, 3, 3));
        tfJabatanPengurus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfJabatanPengurusFocusGained(evt);
            }
        });
        tfJabatanPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJabatanPengurusActionPerformed(evt);
            }
        });

        tfAlamatLengkap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfAlamatLengkap.setMargin(new java.awt.Insets(3, 3, 3, 3));
        tfAlamatLengkap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfAlamatLengkapFocusGained(evt);
            }
        });
        tfAlamatLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlamatLengkapActionPerformed(evt);
            }
        });

        tfNamaPengurus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfNamaPengurus.setMargin(new java.awt.Insets(3, 3, 3, 3));
        tfNamaPengurus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNamaPengurusFocusGained(evt);
            }
        });
        tfNamaPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaPengurusActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel5.setText("Alamat Lengkap");

        jlJabatan.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jlJabatan.setText("Jabatan");

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel7.setText("Kontak");

        jLabel9.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel9.setText("Status Anggota");

        tfTanggalLahir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfTanggalLahir.setMargin(new java.awt.Insets(3, 3, 3, 3));
        tfTanggalLahir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTanggalLahirFocusGained(evt);
            }
        });
        tfTanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTanggalLahirActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel12.setText("Jenis Kelamin");

        btnReset.setActionCommand("Registrasi");
        btnReset.setBackground(new java.awt.Color(244, 182, 25));
        btnReset.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setLabel("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSimpan.setActionCommand("Registrasi");
        btnSimpan.setBackground(new java.awt.Color(28, 200, 138));
        btnSimpan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setLabel("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        cbJenisKelamin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));

        cbStatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Non-Aktif" }));

        tfKontakPengurus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfKontakPengurus.setMargin(new java.awt.Insets(3, 3, 3, 3));
        tfKontakPengurus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfKontakPengurusFocusGained(evt);
            }
        });
        tfKontakPengurus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKontakPengurusActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel15.setText("Tanggal Lahir");

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel8.setText("ID");

        tfKontakPengurus1.setEditable(false);
        tfKontakPengurus1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfKontakPengurus1.setMargin(new java.awt.Insets(3, 3, 3, 3));
        tfKontakPengurus1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfKontakPengurus1FocusGained(evt);
            }
        });
        tfKontakPengurus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKontakPengurus1ActionPerformed(evt);
            }
        });

        btnReset1.setActionCommand("Registrasi");
        btnReset1.setBackground(new java.awt.Color(244, 182, 25));
        btnReset1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnReset1.setForeground(new java.awt.Color(255, 255, 255));
        btnReset1.setLabel("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        btnSimpan1.setActionCommand("Registrasi");
        btnSimpan1.setBackground(new java.awt.Color(28, 200, 138));
        btnSimpan1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSimpan1.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan1.setLabel("Simpan");
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tfJabatanLayout = new javax.swing.GroupLayout(tfJabatan);
        tfJabatan.setLayout(tfJabatanLayout);
        tfJabatanLayout.setHorizontalGroup(
            tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfJabatanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tfJabatanLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfJabatanLayout.createSequentialGroup()
                        .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tfJabatanLayout.createSequentialGroup()
                                .addComponent(tfKontakPengurus1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tfJabatanLayout.createSequentialGroup()
                                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tfJabatanLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(tfJabatanLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(tfJabatanLayout.createSequentialGroup()
                                        .addComponent(tfKontakPengurus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(tfJabatanLayout.createSequentialGroup()
                                                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfNamaPengurus, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlNamaLengkapPengurus))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfJabatanPengurus, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlJabatan)))
                                            .addComponent(jLabel5)
                                            .addComponent(tfAlamatLengkap))
                                        .addGroup(tfJabatanLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(408, 408, 408)
                                            .addComponent(jLabel15))))))
                        .addGap(33, 33, 33))))
        );
        tfJabatanLayout.setVerticalGroup(
            tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfJabatanLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNamaLengkapPengurus)
                    .addComponent(jlJabatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJabatanPengurus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNamaPengurus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAlamatLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(2, 2, 2)
                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTanggalLahir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKontakPengurus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfKontakPengurus1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tfJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Edit Pengurus");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tfJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 381, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(0, 205, Short.MAX_VALUE)
                    .addComponent(tfJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfJabatanPengurusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfJabatanPengurusFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJabatanPengurusFocusGained

    private void tfJabatanPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJabatanPengurusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJabatanPengurusActionPerformed

    private void tfAlamatLengkapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAlamatLengkapFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlamatLengkapFocusGained

    private void tfAlamatLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlamatLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlamatLengkapActionPerformed

    private void tfNamaPengurusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNamaPengurusFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaPengurusFocusGained

    private void tfNamaPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaPengurusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaPengurusActionPerformed

    private void tfTanggalLahirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTanggalLahirFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggalLahirFocusGained

    private void tfTanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTanggalLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggalLahirActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tfKontakPengurusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKontakPengurusFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKontakPengurusFocusGained

    private void tfKontakPengurusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKontakPengurusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKontakPengurusActionPerformed

    private void tfKontakPengurus1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfKontakPengurus1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKontakPengurus1FocusGained

    private void tfKontakPengurus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKontakPengurus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKontakPengurus1ActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_Pengurus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_Pengurus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnReset;
    private java.awt.Button btnReset1;
    private java.awt.Button btnSimpan;
    private java.awt.Button btnSimpan1;
    public javax.swing.JComboBox<String> cbJenisKelamin;
    public javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlJabatan;
    private javax.swing.JLabel jlNamaLengkapPengurus;
    public javax.swing.JTextField tfAlamatLengkap;
    private javax.swing.JPanel tfJabatan;
    public javax.swing.JTextField tfJabatanPengurus;
    public javax.swing.JTextField tfKontakPengurus;
    private javax.swing.JTextField tfKontakPengurus1;
    public javax.swing.JTextField tfNamaPengurus;
    public javax.swing.JTextField tfTanggalLahir;
    // End of variables declaration//GEN-END:variables
}
